spring:
  application:
    name: tduck-api
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mail:
    host: smtp.88.com
    port: 465
    protocol: smtps
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB



server:
  port: 8999
  servlet:
    context-path: /tduck-api

# 日志级别
logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: debug
    com.tduck.cloud: debug

mybatis-plus:
  type-aliases-package: com.tduck.cloud.*.entity
  type-enums-package: com.tduck.cloud.*.entity.enums
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
  # 原生配置
  configuration:
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    map-underscore-to-camel-case: true
    cache-enabled: false


#  请求日志是否打印
platform:
#  request:
#    trace-log: true
  sign:
    enable: true
    secret: 916lWh2WMcbSWiHv
    ignore-urls:
      - /tduck-api/webjars/**
      - /tduck-api/swagger/**
      - /tduck-api/swagger-ui.html
      - /tduck-api/swagger-resources/**
      - /tduck-api/swagger/**
      - /tduck-api/**/v2/api-docs
      - /tduck-api/**/v2/api-docs-ext
      - /tduck-api/doc.html
      - /tduck-api/user/file/upload
      - /tduck-api/project/file/upload/**
      - /tduck-api/wx/mp/portal/**
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
  jwt:
    # 加密秘钥
    secret: f6f31a5f2136758f86b67cde583cb125
    # token有效时长，7天，单位秒
    expire: 604800
    header: token


aj:
  captcha:
    water-mark: tduck

