spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tduck?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mail:
    host: smtp.88.com
    username: mpw:cQlmMGLhCPnF0kA+y1nCw0rm/vJI/jM8cZ3/0IEc6o8=
    password: mpw:ZxqW7Sx4UBreFcrvqab129PeI4cILz74rGFl3o4udb4=

logging:
  level:
    com.tduck.cloud: debug
  config: classpath:logback-spring.xml

platform:
  oss:
    ossType: 1
    endpoint: 12
    accessKeyId: mpw:vT2DiLH0raFqd2+10sAGbvhyYQsWKuxj2YOnXAh+ZhAsMkhqcQBSa5tQosuposvs
    accessKeySecret: mpw:ZRJuLL9+aiBq+9PUN3wjrglLNvuK2yhKhrnSzw5P36P/E9QP4EIOIObeQvYjpaV/
    bucketName: tduck-cloud
    domain: https://qiniu.smileyi.top
  sms:
    secretId: mpw:EvC1LR0eGdzeQzkuO7fhEazxGtmdue8FJDzSA1l+gICuOUEDXI8zcjK+VXB2aWKS
    secretKey: mpw:W3kvWxvHdgUJPAwqR6mwpfMoQMerAYcxZGHwJc259lK3m+jzceGuu0Tgnx++02Bk
    appId: 1400461467
    sign: smileyi知识分享
    validateCodeTemplateId: 808150
    retrievePwdValidateCodeTemplateId: 809014
  front:
    baseUrl: http://localhost:8888/
    resetPwdUrl: http://localhost:8888/forget/password?code={}&email={}
    updateEmailUrl: http://localhost:8888/account/validate?type=updateEmail&code={}&email={}
wx:
  mp:
    redis-config-key-prefix: wx
    configs:
      - appId: mpw:4a4WuGFJwUqxCafqfPwlWGBq+WTgA8Dzpx+5uRNzuUg=
        secret: mpw:P7se5EtBUp0txkSgGFlNG7nz9jluCq++4Tz5DnWpeaCLf1mQV6XXusR0u+ssn6Rg
        token: mpw:4RxTRQGra0TACzttk+84TRsnVhTyG6a/peX0v+KZgyg=
        aesKey:
